version: 0.0
os: linux
files:
  - source: ./dist
    destination: /home/ec2-user/dist
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root
  InstallApplication:
    - location: scripts/make_changes.sh
      timeout: 300
      runas: root
  # CleaningFiles:
  #   - location: scripts/clean.sh
  #     timeout: 300

      
