version: 0.0
os: linux
files:
  - source: .\dist
    destination: /usr/share/nginx/html
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/make_changes.sh
      timeout: 300
      runas: root 

      
