version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/dist
hooks:
  BeforeInstall:
    - location: scripts/stop_service.sh
      timeout: 300
    
  # AfterInstall:
  #   - location: scripts/make_changes.sh
  #     timeout: 300
      
  # ApplicationStart:
  #   - location: scripts/start_server.sh
  #     timeout: 300

      
